apiVersion: v1
kind: Pod
metadata:
  name: scrapper
  labels:
       app: scrapper
spec:
  containers:
  - name: scrapper
    image: artifactory.grepsr.com/scrapper:v1
  # Define resource requirements
    resources:
      limits:
            cpu: 200m
            memory: 64m
      requests:
            cpu: 200m
            memory: 1Gb
      
  # Define node affinity
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: memory
              operator: In
              values:
              - true
